Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

#1 initializing an empty array
empty_array = np.empty((2,2))
print(empty_array)

#2 initializing all ones array
ones_array = np.ones((4,2))
print(ones_array)

#3 returning a new array of given shape and type using fill value
fill_value = 17
filled_array = np.full((2,4), fill_value)
print(filled_array)

#4 returning a new array of zeros
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print(zeros_like_array)

#5 returning a new array of ones
given_array = np.array([[1, 2], [3, 4]])
ones_like_array = np.ones_like(given_array)
print(ones_like_array)

#6 Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(numpy_array)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[17 17 17 17]
 [17 17 17 17]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[1 2 3 4]


Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

#1 creating an array with values ranging from 10 to 49
array_of_range = np.arange(10, 50)
print(array_of_range)

#2 creating a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

#3 creating a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

#4 Creating a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array of size 30:", random_array)
print("Mean of the array:", mean_value)

#5 Creating a 10x10 array with random values and find min & max
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array:\n", random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

#6 creating a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Replacing the 5th element
print(zero_array)

#7 reversing an array arr = [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print(reversed_array)

#8 creating a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)

#9 creating an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Array of size 30: [0.01570901 0.4666976  0.80611811 0.72157588 0.1436184  0.89802717
 0.93244643 0.76351495 0.80755011 0.36865613 0.12682559 0.84018795
 0.14151461 0.59502517 0.30649237 0.83815846 0.41337747 0.08977313
 0.95914526 0.23414596 0.35667821 0.81136076 0.79216948 0.76121138
 0.96268417 0.49947367 0.01092732 0.30872246 0.1228072  0.89082481]
Mean of the array: 0.5328473080374486

10x10 Random Array:
 [[0.69237426 0.28060444 0.51726065 0.56402204 0.43651597 0.88238809
  0.41776337 0.27947003 0.97666295 0.02895451]
 [0.42294076 0.08151732 0.33666862 0.27077657 0.76211125 0.62678891
  0.67441211 0.48789786 0.24991031 0.76128077]
 [0.09463299 0.59949131 0.45183835 0.06414024 0.35279657 0.01130036
  0.65554605 0.71617402 0.6337301  0.74356166]
 [0.59230473 0.70824648 0.40791059 0.08230559 

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#adding the two arrays
array_add = x + y
print(array_add)

#substracting the two arrays
array_sub = x - y
print(array_sub)

#multiplying the array with a number eg- 2
array_mul = x * 2
print(array_mul)

# Find the square of each element of the array.
sqr_arr_y = np.power(y, 2)
print("Square of array y is: \n", sqr_arr_y)

# Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_x_y = np.dot(x,y)
dot_v_w = np.dot(v,w)
dot_x_v = np.dot(x,v)
print("Dot product of x and y: \n", dot_x_y)
print("Dot product of v and w: \n", dot_v_w)
print("Dot product of x and v: \n", dot_x_v)

# Concatenate x(and)y along row and Concatenate v(and)w along column.
concat_x_y = np.concatenate((x,y),axis=0)
stack_x_y = np.vstack((x,y))

stack_v_w = np.hstack((v,w))
print("Concatination of x and y along row: \n", concat_x_y)
print("Stacking of x and y along row: \n", stack_x_y)
print("Stacking of v and w along row: \n", stack_v_w)

#Concatenate x(and)v
#concate_x_v = np.concatenate((x,v),axis=0)

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 2  4]
 [ 6 10]]
Square of array y is: 
 [[25 36]
 [49 64]]
Dot product of x and y: 
 [[19 22]
 [50 58]]
Dot product of v and w: 
 219
Dot product of x and v: 
 [29 77]
Concatination of x and y along row: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Stacking of x and y along row: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Stacking of v and w along row: 
 [ 9 10 11 12]


For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BTAT
.


In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# Prove A.A−1 = I.
A_inverse = np.linalg.inv(A)

mul_A_Ainv = np.dot(A, A_inverse)
print("Multiplication of A and A_inverse: \n", mul_A_Ainv)
idenity_matrix = np.eye(A.shape[0])
print("Identity matrix: \n", idenity_matrix)

is_identity = np.allclose(mul_A_Ainv, idenity_matrix)
if(is_identity):
    print("The matrix multiplication of A and its inverse is an Identity matrix or close to it.")
    print("Hence Proved.")
else:
    print("Not Proved.")

# Prove AB ̸= BA.
mul_AB = np.matmul(A,B)
mul_BA = np.matmul(B,A)
print("Multiplication of A and B: \n", mul_AB)
print("Multiplication of B and A: \n", mul_BA)

equal_mul = np.array_equal(mul_AB, mul_BA)
if(not equal_mul):
    print("The matrix multiplication of A and B is not equal to the matrix multiplication of B and A.")
    print("Hence Proved.")
else:
    print("The matrix multiplication of A and B is equal to the matrix multiplication of b and A.")
    print("Not proved.")

# Prove (AB)T = BTAT
A_transpose = np.transpose(A)
B_transpose = np.transpose(B)
AB_transpose = np.transpose(mul_AB)
print("The Transpose of AB ((AB)T) is: \n", AB_transpose)
B_trans_A_trans = np.matmul(B_transpose, A_transpose)
print("The Transpose of B multiplied with Transpose of A (BTAT) is: \n", B_trans_A_trans)

equal_trans = np.array_equal(AB_transpose, B_trans_A_trans)
if(equal_trans):
    print("The transpose of AB and transpose of B multiplied with transpose of A is equal.")
    print("Hence Proved.")
else:
    print("Not Proved.")


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np

# representing in augmented matrix form

# Matrix of coefficients
a = [
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
    ]
A = np.array(a)

# Matrix of constants
b = [-1,-3,9]
B = np.array(b)

# Using inverse method
A_inverse = np.linalg.inv(A)
X = np.matmul(A_inverse, B)
print("The value of x, y, z is: \n", X)


The value of x, y, z is: 
 [ 2.  1. -2.]


Experiment: How Fast is Numpy?

1. Element-wise Addition
2. Element-wise Multiplication
3. Dot Product
4. Matrix Multiplication

In [ ]:
import numpy as np
import random
from timeit import timeit
#Generating a larger random sample data
size=1000000
#Python lists
Z1_list=random.sample(range(size+1),size)
Z2_list=random.sample(range(size+1),size)
#Numpy arrays
Z1_arr=np.array(Z1_list)
Z2_arr=np.array(Z2_list)

#1. Element-wise addition
def add_python(a,b):
  return [A+B for A,B in zip(a,b)]
def add_numpy(a,b):
  return np.add(a,b)
#Calculating the execution of each function
python_addtime = timeit("add_python(Z1_list,Z2_list)", globals=globals(), number=100)
numpy_addtime = timeit("add_numpy (Z1_arr,Z2_arr)", globals=globals(), number=100)
print(f"Pure Python addition:{python_addtime:.6f} seconds per loop")
print(f"Numpy addition:{numpy_addtime:.6f} seconds per loop")

#2. Element-wise multiplication
def multiply_python(a,b):
  return [A*B for A,B in zip(a,b)]
def multiply_numpy(a,b):
  return a*b
#Calculating the execution of each function
python_multiplytime = timeit("multiply_python(Z1_list,Z2_list)", globals=globals(), number=100)
numpy_multiplytime = timeit("multiply_numpy (Z1_arr,Z2_arr)", globals=globals(), number=100)
print(f"Pure Python multiplication:{python_multiplytime:.6f} seconds per loop")
print(f"Numpy multiplication:{numpy_multiplytime:.6f} seconds per loop")

#3.Dot product
def dot_python(a,b):
  return sum([A*B for A,B in zip(a,b)])
def dot_numpy(a,b):
  return np.dot(a,b)
#Calculating the execution of each function
python_dottime = timeit("dot_python(Z1_list,Z2_list)", globals=globals(), number=100)
numpy_dottime = timeit("dot_numpy(Z1_arr,Z2_arr)", globals=globals(), number=100)
print(f"Pure Python dot product:{python_dottime:.6f} seconds per loop")
print(f"Numpy dot product:{numpy_dottime:.6f} seconds per loop")


# 4. Matrix Multiplication
# Reshape into 2D arrays (e.g., 300 x 300 matrices)
matrix_size =300 # Adjust as needed
Z1_matrix_list = [Z1_list[i:i + matrix_size] for i in range(0, matrix_size ** 2, matrix_size)]
Z2_matrix_list = [Z2_list[i:i + matrix_size] for i in range(0, matrix_size ** 2, matrix_size)]

Z1_matrix_arr = np.array(Z1_matrix_list)
Z2_matrix_arr = np.array(Z2_matrix_list)

def matrix_python(a, b):
    return [
        [sum(A * B for A, B in zip(row_a, col_b)) for col_b in zip(*b)]
        for row_a in a
    ]

def matrix_numpy(a, b):
    return np.matmul(a, b)

# Calculating the execution of each function
python_matrix_time = timeit("matrix_python(Z1_matrix_list, Z2_matrix_list)", globals=globals(), number=10)
numpy_matrix_time = timeit("matrix_numpy(Z1_matrix_arr, Z2_matrix_arr)", globals=globals(), number=10)

print(f"Pure Python matrix multiplication: {python_matrix_time:.6f} seconds per loop")
print(f"NumPy matrix multiplication: {numpy_matrix_time:.6f} seconds per loop")

Pure Python addition:31.744825 seconds per loop
Numpy addition:0.145801 seconds per loop
Pure Python multiplication:31.061537 seconds per loop
Numpy multiplication:0.120919 seconds per loop
Pure Python dot product:33.035948 seconds per loop
Numpy dot product:0.095977 seconds per loop
Pure Python matrix multiplication: 74.033487 seconds per loop
NumPy matrix multiplication: 0.275227 seconds per loop
